### ISSUE TITLE
电脑上显示正常，手机上会重叠在一起

### ISSUE THREAD

**Issue by pipicoming** [WtecHtec/WorkNotes#7]
大佬帮忙看下原因呢，
电脑效果 ：

<img width="226" alt="image" src="https://user-images.githubusercontent.com/23277111/204694908-7b6637e8-e7a6-4596-a610-afcd2b46c5f6.png">

手机效果：
<img width="371" alt="image" src="https://user-images.githubusercontent.com/23277111/204694757-dd936632-459a-4960-9bd9-8ddada80abd0.png">

**Comment by WtecHtec** [comment]
代码看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WtecHtec/WorkNotes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 上午10:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WtecHtec/WorkNotes] 电脑上显示正常，手机上会重叠在一起 (Issue #7)





 
大佬帮忙看下原因呢，
 电脑效果 ：
 
 
手机效果：

**Comment by pipicoming** [comment]
@WtecHtec 
组件：
<img width="708" alt="image" src="https://user-images.githubusercontent.com/23277111/204704683-40b740c2-f21b-4af9-9187-ce14dc0921ea.png">

引用的地方：

<img width="350" alt="image" src="https://user-images.githubusercontent.com/23277111/204704783-6e7c91bf-b524-4dbc-9ffd-ae7df708e766.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/23277111/204704722-72b80081-caae-4e77-8704-b2d512650b23.png">

**Comment by pipicoming** [comment]
@WtecHtec 大佬，能加个联系方式吗？

**Comment by WtecHtec** [comment]
QQ: 504105925




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WtecHtec/WorkNotes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WtecHtec/WorkNotes] 电脑上显示正常，手机上会重叠在一起 (Issue #7)





 
@WtecHtec 大佬，能加个联系方式吗？

**Comment by Tintines** [comment]
居然有人联系我，都没注意到，qq 497763276




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WtecHtec/WorkNotes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 下午3:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [WtecHtec/WorkNotes] 电脑上显示正常，手机上会重叠在一起 (Issue #7)





 
@WtecHtec 大佬，能加个联系方式吗？

**Comment by WtecHtec** [comment]
问题解决了么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WtecHtec/WorkNotes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 晚上7:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WtecHtec/WorkNotes] 电脑上显示正常，手机上会重叠在一起 (Issue #7)





 居然有人联系我，都没注意到，qq 497763276 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "WtecHtec/WorkNotes"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月30日(星期三) 下午3:34 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [WtecHtec/WorkNotes] 电脑上显示正常，手机上会重叠在一起 (Issue #7) 
 
 
 
 
 
   
 @WtecHtec 大佬，能加个联系方式吗？
